language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['kalakris-cmake', 'boost-latest', 'llvm-toolchain-precise', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8', 'llvm-3.8-dev', 'cmake']
      env: BOOST_VERSION=1.59.0 COMPILER=clang-3.8 CXXCOMPILER=clang++-3.8

install:
  # DEPENDENCIES (see https://github.com/boostorg/hana/blob/master/.travis.yml)

  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install Boost headers
  ############################################################################
  - |
    if [[ ! -f ${DEPS_DIR}/boost/bootstrap.sh ]]; then

     if [[ "${BOOST_VERSION}" == "1.57.0" ]]; then BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz"; fi
     if [[ "${BOOST_VERSION}" == "1.58.0" ]]; then BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz"; fi
     if [[ "${BOOST_VERSION}" == "1.59.0" ]]; then BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz"; fi
     if [[ "${BOOST_URL}" != "" ]]; then mkdir -p boost && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost; fi

     if [[ "${BOOST_VERSION}" == "trunk" ]]; then
       BOOST_URL="http://github.com/boostorg/boost.git"
       travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL}
     fi

     (cd boost && ./bootstrap.sh --prefix="${DEPS_DIR}/boost" --with-libraries=program_options,filesystem,system,regex && ./b2 -d0 install)
    fi

  - if [[ -d ${DEPS_DIR}/boost ]]; then CMAKE_OPTIONS+=" -DBOOST_ROOT=${DEPS_DIR}/boost"; fi

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

  ############################################################################
  # Install Boost.Build
  ############################################################################
  - |
    if [[ "${BOOST_BUILD}" == "true" ]]; then
      (cd boost/tools/build && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2)
      export PATH=${DEPS_DIR}/b2/bin:${PATH}
    fi

  - cd ${TRAVIS_BUILD_DIR}

  - ./setup.sh
  - mkdir build && cd build

script:
  - cmake ../ -DCMAKE_C_COMPILER=$COMPILER -DCMAKE_CXX_COMPILER=$CXXCOMPILER ${CMAKE_OPTIONS}
  - make CC=$COMPILER CXX=$CXXCOMPILER all test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost
